apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    topix.service: topix-api
  ports:
  - name: "api-service-port"
    protocol: TCP
    port: 80
    targetPort: {{ .Values.api.port }}
status:
  loadBalancer: {}
