apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  type: NodePort
  selector:
    topix.service: topix-api
  ports:
  - name: "api-service-port"
    protocol: TCP
    port: 80
    targetPort: {{ .Values.api.port }}
status:
  loadBalancer: {}
