apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: topix-api-ingress
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
 rules:
 - host: {{ .Values.api.ingress.host }}
   http:
     paths:
     - path: /topix-api/*
       backend:
         serviceName: "api-service"
         servicePort: 80
