apiVersion: v1
kind: Service
metadata:
  name: topix-api-service
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  type: NodePort
  selector:
    app: topix-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.api.port }}
status:
  loadBalancer: {}
