apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          value: {{ .Values.env.mongo_username }}
        - name: ADMIN_PASS
          value: {{ .Values.env.mongo_password }}
        - name: APPLICATION_DATABASE
          value: {{ .Values.env.mongo_database }}
        - name: APPLICATION_USER
          value: {{ .Values.env.mongo_username }}
        - name: APPLICATION_PASS
          value: {{ .Values.env.mongo_password }}
        - name: AUTH
          value: "yes"
        image: vepo/mongo
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodata
      restartPolicy: Always
      volumes:
      - name: mongodata
        persistentVolumeClaim:
          claimName: mongodata
status: {}
