apiVersion: v1
kind: Service
metadata:
  name: mongodb
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
status:
  loadBalancer: {}
