apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  metadata:
    annotations:
      timestamp: "{{ date "20060102150405" .Release.Time }}"
  ports:
  - name: "mondb-service-port"
    port: 27017
    targetPort: 27017
  selector:
    topix.service: mongodb
status:
  loadBalancer: {}
