apiVersion: v1
kind: Service
metadata:
  name: mongodb
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  ports:
  - name: "mondb-service-port"
    port: 27017
    targetPort: 27017
  selector:
    topix.service: mongodb
status:
  loadBalancer: {}
