apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
spec:
  metadata:
    annotations:
      timestamp: "{{ date "20060102150400" .Release.Time }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
