apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  ports:
  - name: "redis-service-port"
    port: 6379
    targetPort: 6379
  selector:
    topix.service: redis
status:
  loadBalancer: {}
