apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    topix.service: topix-redis-data
  name: topix-redis-data
  annotations:
    timestamp: "{{ date "20060102150400" .Release.Time }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
