apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    topix.service: topix-redis-data
  name: topix-redis-data
spec:
  metadata:
    annotations:
      timestamp: "{{ date "20060102150400" .Release.Time }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
